version: '3.8'

services:

    pg2b3dm-postgis:
        container_name: pg2b3dm-postgis
        build:
            context: ./postgis
            args:
                - POSTGRES_VERSION
                - POSTGIS_VERSION
        environment:
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_HOST_AUTH_METHOD=trust
        # Exposition du port de la base de données pour test si nécessaire
        # ports:
        #     - "5433:5432"
        volumes:
            - parcellaire-postgis-data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
            interval: 10s
            timeout: 5s
            retries: 5

    pg2b3dm-adminer:
        container_name: pg2b3dm-adminer
        image: adminer:4.8.1
        ports:
            - "8080:8080"
        environment: 
           - ADMINER_DEFAULT_SERVER=${POSTGRES_HOST}
           - ADMINER_DESIGN=hydra
        depends_on:
            pg2b3dm-postgis:
                condition: service_healthy

    pg2b3dm-importer:
        container_name: pg2b3dm-importer
        build:
            context: ./importer
        environment:
            - POSTGRES_USER
            - POSTGRES_DB
            - POSTGRES_HOST
            - POSTGRES_SCHEMA
        volumes:
            - importer-data:/tmp
        depends_on:
            pg2b3dm-postgis:
                condition: service_healthy
        
    pg2b3dm:
        container_name: pg2b3dm
        image: geodan/pg2b3dm:2.8.0
        environment:
            - POSTGRES_USER
            - POSTGRES_DB
            - POSTGRES_HOST
        command:
            pg2b3dm -h $POSTGRES_HOST -U $POSTGRES_USER -c geom -d $POSTGRES_DB -t sibbe -a identificatie -o /output
        volumes:
            - type: bind
              source: ./output
              target: /output
        depends_on:
            pg2b3dm-importer:
                condition: service_completed_successfully
            
volumes:
    parcellaire-postgis-data:
        name: parcellaire-postgis-data
    importer-data:
        name: importer-data
